### ISSUE TITLE
Update surface components page so it doesn't bleed in to demo toolbar

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/angular-showcase-demo#148]
#### Describe the bug
On the Brightlayer UI Surface Components page, the AppBar examples are overflowing the Demo's pinned toolbar (top).
Also the AppBar section is labeled incorrectly.  It is currently labeled "ChannelValue" but should be updated to be "AppBar".

#### What is the expected behavior?
The AppBar examples should not be overflow the toolbar; the should appear behind it.

#### What are the steps to reproduce?
1. Clone this repo
2. Run `yarn && yarn start`
3. Navigate to http://localhost:4200/blui-components/surface-components
4. Scroll down and observe that the toolbar example is overflow the screen's pinned appbar.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/171271316-9ba27ddb-ca7d-4168-bec1-80fdf5676c14.png)

#### Environment

Chrome, Windows

**Comment by ektasawant** [comment]
Increase z-index of main app bar.

**Comment by Abhyuday03** [comment]
Hey, I would like to work on this issue. Please assign me this issue

**Comment by emclaug2** [comment]
> Hey, I would like to work on this issue. Please assign me this issue

All yours, thanks @Abhyuday03 👍

**Comment by emclaug2** [comment]
Fixed in #259
