### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-showcase-demo#29]
Describe the desired behavior
Check the current/latest version of all dependencies and peer dependencies. Update the package.json to include the latest.

Describe the current behavior
Using old versions of dependencies.

Is this request related to a current issue?
The newest version of NPM (npm version 7) fails on npm install (instead of a warning) when there are peer dependency issues.

Additional Context
After updating the versions of dependencies, make sure that things still work as expected.

**Comment by joebochill** [comment]
Let's take another look at this and see if it has been addressed.

**Comment by joebochill** [comment]
It'll be a good opportunity to try to address this when we do the showcase design overhaul story.

**Comment by emclaug2** [comment]
Fixed in #54 ; all dependencies are updated.
