### ISSUE TITLE
Change Tag Colors 

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-showcase-demo#41]
#### Describe the bug
On the showcase 
The tag colors in the picture below look incorrect.

#### What is the expected behavior?
Adjust the "Acknowledged" & "Closed" tag to be less straining on the eyes. 

#### What are the steps to reproduce?
1. Clone the repo and cd into the project.
2. Run `yarn && yarn start`.
3. Navigate to the Alarms page. 
4. Switch to dark-mode using the top-right icon in the app bar.
5. Observe the tags in dark-mode

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/140181161-f7f6c791-98e4-4b5b-90e7-fbae5cec4aef.png)

#### Environment

Chrome, Windows
		
#### Anything else to add?
Discovered here:
https://github.com/pxblue/angular-component-library/pull/358

**Comment by emclaug2** [comment]
Currently the colors are hard-coded for both themes; add a light/dark theme color set.

**Comment by amanchoudhary18** [comment]
Hi, I would love to work on this issue. I can create an obj for dark colors and apply the class obj using a function. Assign it to me..

**Comment by emclaug2** [comment]
> Hi, I would love to work on this issue. I can create an obj for dark colors and apply the class obj using a function. Assign it to me.

Hey @amanchoudhary18 I'll assign the issue to you; it might be helpful to create a themeService that keeps track of this light/dark state.  

Thanks 👍

**Comment by emclaug2** [comment]
Fixed in #260
