### ISSUE TITLE
Firefox not loading any fonts due to security concerns

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-showcase-demo#82]
#### Describe the bug

Things look fine in Chrome and Safari. In Firefox, however, fonts are not loaded. Icon fonts are falling back to text, and Open Sans is falling back to Arial.

#### What is the expected behavior?

Should load.

#### What are the steps to reproduce?
1. yarn start

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/8997218/160151245-e0c3e410-63a2-4df2-98a2-6c8f162cc28d.png)

Firefox says this in the inspector:
```
An error occurred: MOZILLA_PKIX_ERROR_MITM_DETECTED
```
![image](https://user-images.githubusercontent.com/8997218/160151385-5f369a34-3f4c-4521-abf9-3ff7e2971938.png)

#### Environment
Mac Firefox

**Comment by bkarambe** [comment]
The issue only happens only in localhost. If this site is hosted remotely, the fonts load.

**Comment by jeffvg** [comment]
Can not duplicate the same issue running locally on dev branch today. This might have been a proxy issue..
![image](https://user-images.githubusercontent.com/37150565/163185145-487150b8-bb0d-4a6d-9de5-a8d8828ba0ea.png)
